apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ .Values.mysqlSecretName }}
  labels:
    {{- include "mysql-rrc.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.mysqlSecretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $mysqlRootPassword := (get $secretData "MYSQL_ROOT_PASSWORD") | default (.Values.mysqlRootPassword | b64enc) | default (randAlphaNum 32 | b64enc) }}
  {{- $mysqlPassword := (get $secretData "MYSQL_PASSWORD") | default (.Values.mysqlPassword | b64enc) | default (randAlphaNum 32 | b64enc) }}
  {{- $mysqlReplicaPassword := (get $secretData "MYSQL_SOURCE_PASSWORD") | default (.Values.mysqlReplicaPassword | b64enc) | default (randAlphaNum 32 | b64enc) }}
  {{- $mysqlClonePassword := (get $secretData "MYSQL_BACKUP_PASSWORD") | default (.Values.mysqlClonePassword | b64enc) | default (randAlphaNum 32 | b64enc) }}
  {{- $mysqlUser := (get $secretData "MYSQL_USER") | default (.Values.mysqlUser | b64enc ) | default ("test" | b64enc) }}
  {{- $mysqlDatabase := (get $secretData "MYSQL_DATABASE") | default (.Values.mysqlDatabase | b64enc) | default ("test" | b64enc) }}
  {{- $mysqlReplicaUser := (get $secretData "MYSQL_SOURCE_USER") | default (.Values.mysqlReplicaUser | b64enc) | default ("replicauser" | b64enc) }}
  {{- $mysqlCloneUser := (get $secretData "MYSQL_BACKUP_USER") | default (.Values.mysqlCloneUser | b64enc) | default ("backupuser" | b64enc) }}
  MYSQL_ROOT_PASSWORD: {{ $mysqlRootPassword | quote }}
  MYSQL_USER: {{ $mysqlUser | quote }}
  MYSQL_PASSWORD: {{ $mysqlPassword | quote }}
  MYSQL_DATABASE: {{ $mysqlDatabase | quote }}
  MYSQL_SOURCE_USER: {{ $mysqlReplicaUser | quote }}
  MYSQL_SOURCE_PASSWORD: {{ $mysqlReplicaPassword | quote }}
  MYSQL_BACKUP_USER: {{ $mysqlCloneUser | quote }}
  MYSQL_BACKUP_PASSWORD: {{ $mysqlClonePassword | quote }}
  RRC_HLSERVICE: {{ .Values.headlessServiceName | b64enc | quote }}
{{- if .Values.imagePullSecrets }}
{{- range $pullSecret := .Values.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ $pullSecret.name }}
  labels:
    {{- include "mysql-rrc.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData: 
  .dockerconfigjson: |-
    {
      "auths": {
        {{ $pullSecret.registryURL | quote }}: {
          "auth": {{ $pullSecret.accessToken | quote }}
        }
      }
    }
{{- end }}    
{{- end }}